"use client";
import { useState } from "react";
import Image from "next/image";
import Link from "next/link";

export default function NewspaperProof() {
  const [wide, setWide] = useState(false);
  return <main id="content" className="workspace-main newspaper-desk">
    <header className="desk-heading newspaper-controls"><p className="desk-eyebrow">The print desk</p><h1>A place in the paper.</h1><p className="desk-intro">A full editorial page with The Swinging Door cartoon in context. Check the size, the caption and how the drawing reads beside a column of type.</p></header>
    <div className="newspaper-toolbar newspaper-controls"><div className="paper-size-switch" role="group" aria-label="Cartoon width"><button type="button" aria-pressed={!wide} onClick={()=>setWide(false)}>Two columns</button><button type="button" aria-pressed={wide} onClick={()=>setWide(true)}>Three columns</button></div><button type="button" className="desk-button" onClick={()=>window.print()}>Print this page / Save PDF</button><a href="/studio-print/newspaper-editorial-proof.pdf" download className="desk-button secondary">Download 11 × 17 proof</a></div>
    <p className="desk-small newspaper-controls proof-notice">Original layout proof, not an issued newspaper. The cartoon is from the existing archive; its headline is part of that older artwork. The surrounding text is original editorial sample copy.</p>
    <article className={`newspaper-sheet${wide ? " newspaper-wide" : ""}`} aria-label="The Swinging Door editorial newspaper proof">
      <header className="paper-masthead"><div className="paper-overline"><span>The Naples edition</span><span>Opinion · Markets · Everyday life</span></div><p className="paper-name">The Swinging Door</p><div className="paper-folio"><span>Thursday, September 3, 2026</span><strong>OPINION & PERSPECTIVE</strong><span>Page 1</span></div></header>
      <div className="paper-lead"><p className="paper-kicker">The editorial page</p><h1>Where the headlines<br />meet the household.</h1><p>The numbers make the news. What we make of them is another story.</p></div>
      <div className="paper-columns">
        <section className="paper-column paper-left"><h2>The price of paying attention</h2><p className="paper-byline">From the editor’s desk</p><p className="paper-dropcap">A financial headline can travel halfway around the world before it reaches the kitchen table. By then, it has acquired a different unit of measurement: a monthly payment, an insurance renewal or the price on a familiar menu.</p><p>That is where this page begins. The economy is more than a chart on a screen. It is also the small calculation before a decision and the conversation that follows it.</p><p>In Naples, there is room for a financial cartoon that recognizes those conversations without turning every reader into an analyst. A good drawing needs an observation. A good caption leaves something for the reader to discover.</p><h3>A smaller stage</h3><p>The Swinging Door gives that conversation a room of its own. Drew supplies the dry observation. Barclay brings the bill back to human scale. Abby has heard enough of both to know when the discussion is over.</p><p>The bar is a setting for the joke, not its subject. The subject is the distance between an announcement and the ordinary day it eventually reaches.</p><p>There is no need to shout across that distance. Sometimes the quietest sentence carries furthest.</p></section>
        <figure className="paper-cartoon"><div className="paper-cartoon-label"><strong>The Swinging Door</strong><span>An editorial cartoon</span></div><Image src="/gallery/final/A01-preview.jpg" width={900} height={1125} alt="Drew holds his martini while Barclay looks toward him; the television above the liquor shelves shows an empty waiting room and an archived rate-hike headline." priority /><figcaption><span>Barclay:</span> “I don’t mind a rate hike. I’d just like two years of waiting for a cut counted as time served.”</figcaption><p className="paper-art-credit">The Swinging Door · Archive artwork A01</p><div className="paper-pullquote">“The conversation is local.<br />The absurdity travels.”</div></figure>
        <aside className="paper-column paper-right"><p className="paper-kicker">Around the table</p><h2>A number is only the beginning</h2><p>A house can have a market value, an assessed value and a taxable value. An insurance quote can look simple until the coverage is compared. A familiar asking price can imply an unfamiliar payment.</p><p>Those distinctions are worth explaining. They are also fertile ground for a cartoon, provided the joke rests on the difference itself and not on somebody’s misfortune.</p><h3>What earns a place here</h3><p>A specific observation. A clear visual scene. Characters with different ways of seeing the same piece of news. A line short enough to read once and interesting enough to read again.</p><p>The point is recognition: that slight pause when a reader realizes the person at the next stool has been doing the same arithmetic.</p><div className="paper-note"><h3>Three seats.<br />One conversation.</h3><p><strong>Drew</strong><br />The measured observer.</p><p><strong>Barclay</strong><br />The number on the receipt.</p><p><strong>Abby</strong><br />The last word, when needed.</p></div></aside>
      </div>
      <footer className="paper-footer"><span>The Swinging Door · Naples editorial design proof</span><span>Original sample copy · Not a published edition</span></footer>
    </article>
    <div className="newspaper-controls newspaper-production"><h2>Before it goes to a newspaper</h2><p>This proof is set on an 11 × 17 inch page. Its 900 × 1,125 pixel archive image is suitable for judging placement; the newspaper’s final column width, resolution and grayscale requirements still need to be confirmed. Changing the width above changes the page proof only.</p><Link href="/library" className="desk-text-link">Find the artwork and source versions →</Link></div>
  </main>;
}
