"use client";
import Image from 'next/image';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import type {BestOfCartoon} from '@/lib/best-of-cartoons';
import {PRINT_SIZES,PRINT_PAPERS,printMetrics,type PrintSizeId,type PrintPaperId} from '@/lib/cartoon-print';
import PresentationShow from './PresentationShow';
const INITIAL=['austin-taking-offers','los-angeles-view-included','professional-opposition','individual-flakes','quiet-arrivals','divide-the-credit'];
const displayTitle=(title:string)=>title.replace(/\b\w/g,letter=>letter.toUpperCase());
export default function PresentationStudio({cartoons,canManage}:{cartoons:BestOfCartoon[];canManage:boolean}) {
  const [index,setIndex]=useState(0),[selected,setSelected]=useState<string[]>(()=>INITIAL.filter(id=>cartoons.some(c=>c.id===id))),[size,setSize]=useState<PrintSizeId>('fine'),[paper,setPaper]=useState<PrintPaperId>('letter'),[newspaper,setNewspaper]=useState(false),[slideshow,setSlideshow]=useState(false),[busy,setBusy]=useState(false),[progress,setProgress]=useState(''),[error,setError]=useState('');
  const stage=useRef<HTMLDivElement>(null);const c=cartoons[index];
  const returnFocus=useRef<HTMLElement|null>(null);
  const metrics=printMetrics(c.width,c.height,size,paper);
  useEffect(()=>{if(!slideshow)return;
    const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';stage.current?.focus();
    const onKey=(event:KeyboardEvent)=>{
      if(event.key==='ArrowRight'){event.preventDefault();setIndex(i=>(i+1)%cartoons.length);}
      if(event.key==='ArrowLeft'){event.preventDefault();setIndex(i=>(i+cartoons.length-1)%cartoons.length);}
      if(event.key==='Escape')void leave();
      if(event.key==='Tab'){
        const buttons=stage.current?.querySelectorAll<HTMLButtonElement>('button:not(:disabled)');if(!buttons?.length)return;
        const first=buttons[0],last=buttons[buttons.length-1];
        if(event.shiftKey&&(document.activeElement===first||document.activeElement===stage.current)){event.preventDefault();last.focus();}
        else if(!event.shiftKey&&(document.activeElement===last||document.activeElement===stage.current)){event.preventDefault();first.focus();}
      }
    };window.addEventListener('keydown',onKey);return()=>{window.removeEventListener('keydown',onKey);document.body.style.overflow=oldOverflow;returnFocus.current?.focus();};
  },[slideshow,cartoons.length]);
  useEffect(()=>{const changed=()=>{if(!document.fullscreenElement)setSlideshow(false);};document.addEventListener('fullscreenchange',changed);return()=>document.removeEventListener('fullscreenchange',changed);},[]);
  useEffect(()=>{setProgress('');setError('');},[selected,size,paper,newspaper]);
  async function present(){returnFocus.current=document.activeElement as HTMLElement;setError('');setSlideshow(true);try{await stage.current?.requestFullscreen();}catch{/* In-page slides remain available if fullscreen is unavailable. */}}
  async function leave(){setSlideshow(false);if(document.fullscreenElement)try{await document.exitFullscreen();}catch{/* The browser may already have handled Escape. */}}
  async function pdf(){setBusy(true);setError('');setProgress('Loading originals…');try{const {showcasePDF}=await import('@/lib/showcase-pdf');const bytes=await showcasePDF(cartoons.filter(c=>selected.includes(c.id)),size,paper,newspaper,(n,total)=>setProgress(`Prepared ${n} of ${total} pages`));const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download=`swinging-door-${newspaper?'newspaper-layout':size}-${selected.length}-cartoons.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);setProgress(`Your ${selected.length}-cartoon PDF is ready. Check your downloads and print at Actual size.`);}catch(e){setError(e instanceof Error?e.message:'PDF could not be prepared.');setProgress('');}finally{setBusy(false);}}
  function toggle(id:string){if(busy)return;setError('');if(!selected.includes(id)&&selected.length>=12){setError('A packet can contain up to 12 cartoons. Remove one before adding another.');return;}setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);}
  return <main className="rick-showcase" id="content">
    <PresentationShow cartoons={cartoons} canManage={canManage}/>
    <header className="showcase-intro"><div><p className="showcase-kicker">A presentation for Rick</p><h1>One familiar room.<br/>A new reason to look.</h1><p>Warm, observant cartoons about money and everyday life. A repeatable production system that can explore a different place with each edition.</p><div className="showcase-actions"><Link className="showcase-primary" href="/gallery/automation">Generate a local edition</Link><button onClick={()=>void present()}>Present the cartoons</button></div></div><Image src={(cartoons.find(c=>c.id==='professional-opposition')||cartoons[0]).previewSrc} width={512} height={768} alt="The Swinging Door cartoon with familiar cast, television story, chalkboard and caption" priority/></header>
    <nav className="showcase-sections" aria-label="Presentation sections"><a href="#cartoon-presentation">Cartoons & print sizes</a><a href="#system">How it works</a><a href="#downloads">PDF & PowerPoint</a><Link href="/gallery/cast">Meet the cast</Link></nav>
    <section id="cartoon-presentation"><div className="showcase-section-head"><h2>The collection, on screen and in print</h2><p>{cartoons.length} cartoons · black and white throughout</p></div>
      <div className="showcase-viewer-layout"><aside className="showcase-controls"><label>Choose a cartoon<select value={index} onChange={e=>setIndex(Number(e.target.value))}>{cartoons.map((item,i)=><option key={item.id} value={i}>{item.cityLabel?`${item.cityLabel} — `:''}{displayTitle(item.title)}</option>)}</select></label><label>Artwork size<select value={size} disabled={busy} onChange={e=>setSize(e.target.value as PrintSizeId)}>{PRINT_SIZES.map(s=><option key={s.id} value={s.id}>{s.width} × {s.height} in — {s.label}</option>)}</select></label><label>Paper<select value={paper} disabled={newspaper||busy} onChange={e=>setPaper(e.target.value as PrintPaperId)}>{PRINT_PAPERS.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label className="showcase-checkbox"><input type="checkbox" checked={newspaper} disabled={busy} onChange={e=>setNewspaper(e.target.checked)}/> Preview in a newspaper</label>
        <p><strong>{metrics.ppi} effective PPI</strong><br/>{c.width} × {c.height} original pixels</p><p className="showcase-note">{metrics.ppi>=300?'Fine-detail size: approximately 300 PPI.':'This larger size has less pixel detail per inch. Check a physical proof before press.'} Screen previews fit your device. The PDF keeps the exact dimensions.</p>
        <Link href={`/gallery/best-of/print/${c.id}`}>Print this cartoon individually</Link><button disabled={busy} onClick={()=>toggle(c.id)}>{selected.includes(c.id)?'Remove from PDF packet':'Add to PDF packet'}</button><p className="showcase-note">{selected.length} of 12 selected. Choose cartoons below to build a packet.</p>
      </aside>
      <div className={`showcase-stage ${slideshow?'showcase-slideshow':''}`} ref={stage} tabIndex={-1} role={slideshow?'dialog':undefined} aria-modal={slideshow?true:undefined} aria-label={slideshow?'Cartoon presentation':undefined}>
        <div className="showcase-viewer-toolbar"><button onClick={()=>setIndex(i=>(i+cartoons.length-1)%cartoons.length)} aria-label="Previous cartoon">←</button><span aria-live="polite">{index+1} / {cartoons.length} · {c.cityLabel||displayTitle(c.title)}</span><button onClick={()=>setIndex(i=>(i+1)%cartoons.length)} aria-label="Next cartoon">→</button>{slideshow?<button onClick={()=>void leave()}>Exit slides</button>:<button onClick={()=>void present()}>Full-screen slides</button>}</div>
        {slideshow?<Image className="showcase-slide-image" key={c.id} src={c.src} width={c.width} height={c.height} alt={c.caption} unoptimized/>:<div className="showcase-paper-area"><div className={`showcase-paper ${newspaper?'showcase-newspaper':''}`} style={{aspectRatio:newspaper?'11 / 17':`${metrics.paper.width} / ${metrics.paper.height}`}}>
          {newspaper&&<><header><h3>THE LOCAL EDITION</h3><p>FICTIONAL MASTHEAD · NEWSPAPER LAYOUT STUDY</p><h4>Money & everyday life</h4></header><div className="showcase-news-copy" style={{width:`${(11-metrics.width-1.35)/11*100}%`}}><h4>A place for the next good line</h4><p>This is an editor’s layout study, not a news report. The space beside the cartoon represents the surrounding newspaper page.</p><p>A familiar room gives readers a recurring destination. A new subject gives them a reason to return.</p><p>The cartoon remains in its original proportions. Compare print sizes to judge its prominence alongside editorial copy.</p><p>Confirm column widths and reproduction requirements with the publication before press.</p></div></>}
          <Image className="showcase-paper-art" src={c.src} width={c.width} height={c.height} alt={c.caption} unoptimized style={newspaper?{width:`${metrics.width/11*100}%`,right:'4.8%',top:'15%'}:{width:`${metrics.width/metrics.paper.width*100}%`,left:'50%',top:'50%',transform:'translate(-50%,-50%)'}}/>
          {newspaper&&<p className="showcase-newspaper-footer">11 × 17 inch layout proof · Not a published newspaper or an endorsement</p>}
        </div></div>}
        {!slideshow&&<p className="showcase-art-caption">{c.speaker} speaking · {c.variant} · {c.caption}</p>}
      </div></div>
      <div className="showcase-selection" aria-busy={busy}><h3>Build your PDF packet</h3><p>Select up to 12. Each cartoon gets its own page at the size chosen above, in collection order.</p><div className="showcase-packet-actions"><strong>{selected.length} of 12 selected</strong><button disabled={busy||!selected.length} onClick={()=>setSelected([])}>Clear selection</button><button disabled={busy} onClick={()=>setSelected(INITIAL.filter(id=>cartoons.some(c=>c.id===id)))}>Use featured six</button></div><div className="showcase-selection-grid">{cartoons.map((item,i)=><div className="showcase-selection-item" key={item.id}><label><input type="checkbox" aria-label={`Include ${displayTitle(item.title)}`} disabled={busy} checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/><Image src={item.previewSrc} width={40} height={60} alt="" loading="lazy"/><span>{displayTitle(item.title)}{item.cityLabel&&<small>{item.cityLabel}</small>}</span></label><button type="button" aria-label={`Preview ${item.title}`} onClick={()=>{setIndex(i);document.getElementById('cartoon-presentation')?.scrollIntoView({behavior:'smooth'});}}>View</button></div>)}</div><button className="showcase-primary" onClick={()=>void pdf()} disabled={busy||!selected.length}>{busy?'Preparing originals…':`Download ${selected.length}-cartoon ${newspaper?'newspaper':'print'} PDF`}</button><p role="status">{progress}</p>{error&&<p role="alert">{error}</p>}</div>
    </section>
    <section id="system" className="showcase-system"><h2>From a place to a finished cartoon</h2><ol><li><strong>Choose the edition</strong><p>City, state, and quantity. Generate starts a saved request. Advanced controls support dated and recurring plans.</p></li><li><strong>Find a subject and a good line</strong><p>The worker researches dated local subjects, drafts a caption, and checks grammar, tone, originality, and the connection to the television and chalkboard.</p></li><li><strong>Make the artwork</strong><p>The local RTX 4090 generates black-and-white television art. The speaker and listeners come from the matching retained cast pose. Chalk and dialogue are laid out precisely.</p></li><li><strong>Review the result</strong><p>Verified images appear automatically. Evidence and production records stay with the request. Machine checks assist an editor; they do not replace your approval.</p></li></ol><p className="showcase-note">The website runs on Vercel from GitHub. Supabase retains the queue and image files. The local worker performs generation. If it is offline, requests wait. Completed stages are checkpointed for recovery. A dedicated always-on GPU host can replace the PC later.</p><Link className="showcase-primary" href="/gallery/automation">Try the live generation flow</Link></section>
    <aside className="showcase-release-note" aria-label="Production rollout status"><strong>Rollout status · September 15, 2026</strong><p>The gallery and this presentation use the approved Barclay corrections. The PC’s scheduled worker still uses the earlier release. Activating the updated worker is the remaining step before new automated editions use the same corrected cast. Check this before the live demonstration.</p></aside>
    <section id="downloads" className="showcase-downloads"><h2>Take the presentation with you</h2><p>Use “Start presentation” for the selected cartoons and live demonstration. The downloadable ten-slide system overview is an earlier companion deck; use the packet builder above for your own selection from the collection.</p><div><a href="/gallery/presentation-20260915/rick-system-showcase.pdf" download>Download the system overview PDF</a><a href="/gallery/presentation-20260915/rick-system-showcase.pptx" download>Download the system overview PowerPoint</a><Link href="/gallery/cast/print/all">Print the illustrated cast dossiers</Link></div><p className="showcase-note">All cartoons use original-resolution grayscale artwork. Newspaper pages are layout studies, not evidence of publication. Print sizing preserves each complete image and caption.</p></section>
  </main>;
}
