#!/usr/bin/env bash
# ABBY ROUND 4 -> the founder's report for 2026-09-06. The new Picture 2 tile,
# the six renders and the contact sheet.
set -eu

PY="C:/Python313/python.exe"
L="Z:/ImageGenerator/Cartoon/scripts/report-log.py"
D="C:/Users/admin/AppData/Local/Temp/claude/Z--ImageGenerator/7e90a839-5703-42df-8007-3e3f206ae0ae/scratchpad/cast-studies/abby/round-4"

SET="local/qwen-image-edit-2511, 4:5 1344x1680, fast Lightning 8 steps, cfg 1, euler/simple, shift 3.0, 3 references (Picture 1 the approved blank plate canon/plates/trio.png cut x60..1140 y20..1370, unchanged from round 3; Picture 2 NEW - the sc04 and sc12 head-and-shoulders crops of the plates Rick accepted, laid side by side in one tile; Picture 3 the hand-drawn eye chart, kept), scripts/cast-study.py --cast-count 3 --keep-duo with nineteen numbered EDITS"

ASK="Round 4 of perfecting Abby. The judges called the references the disease, not the seeds: DROP canon/vision/studies/abby.png and canon/characters/abby/kit/bust.png outright - both draw the silky long coat, the wide lynx-tufted ears and the open-blouse cleavage that all six round-3 renders copied, and round 3 was still sending bust.png as Picture 2, which is where the Bichon came from. Replace them with crops of the plates Rick actually accepted, sc04 (470,360,820,900) and sc12 (450,350,830,930). Keep Picture 1 and the eye chart. Then fix, as EDIT lines: the eye pasted from the chart with a paper-white crescent at BOTH corners; the long fur stopping dead at the jaw; the closed-lip smile with no gap; the gaze on Drew and never on the reader; the harsh short double coat at a third the length; the broad flat-topped chrysanthemum head and blunt rectangular bearded muzzle; the small close-set erect triangular ears; the furred neck carrying the collar; the heavy black studded collar with a heart pendant; the buttoned blouse over a modest chest; grey modelling under the jaw; the back bar in wood grain with legible bottles; a clean straight edge on all four sides. And Drew, in the same plate: downy dash-strokes instead of scales, one S-curve with a single reversal, a heavy-lidded human eye. Hold the recipe - cfg 1 is correct - and re-run the same six seeds for a clean A/B."

T_COMMON="THE REFERENCE SWAP IS THE ROUND. bust.png and studies/abby.png are gone; Picture 2 is now the two head-and-shoulders crops of Rick's accepted plates in one tile. ONE FORCED DEVIATION FROM THE ORDER: the judges asked for the sc12 crop as a PICTURE 4, but the qwen family's max_refs is 3 on the bridge (backend/providers/local_bridge.py) and it drops extras off the END of the list, so a Picture 4 would have been binned on the wire and the round would have LOOKED like it tested the sc12 head without ever sending it. Both ordered crops therefore travel side by side in ONE tile, at the judges' own boxes, and both are genuinely on the wire. SECOND DEVIATION: four legible bottle labels inside the sc04 crop (EAGLE EYE VODKA and its neighbours) were blanked to plain paper first - round 3 proved at seed 55 that lettering inside a reference is copied and then elaborated into pseudo-text at cfg 1, which check 17 calls fatal - and canon asks a study's labels to be blank panels anyway. A BUG WAS ALSO FIXED: --cast-count was parsed and written into the sidecar but never reached the prompt, so round 3 told the model 'EXACTLY 1 character' while its Picture 1 was a three-character plate and its own EDITS said to keep Drew and Barclay; the header now says 3."

# --- the new Picture 2 tile ---------------------------------------------------
"$PY" "$L" --date 2026-09-06 \
  --title "Abby round 4 - the new Picture 2: the plates Rick accepted, in place of the kit tiles" \
  --ask "$ASK" \
  --thought "The judges were exact about the diagnosis and I agree with it: every Abby tile in the repository draws the wrong dog. bust.png and head.png both carry a long silky coat, big wide-set ears with lynx tufts and a round lapdog skull, and the model copied all of it faithfully for three rounds. The plates Rick ACCEPTED draw the right dog - sc04 and sc12 both give a broad flat-topped skull, small hard triangular ears set close on top, a short blunt rectangular muzzle with a beard fringe hanging below it, a heavy black studded collar and a buttoned blouse. So the tile is built from those two crops at the judges' own boxes. I could not send them as Picture 2 and Picture 4 as ordered, because the bridge caps the qwen family at three references and silently drops the rest off the end of the list - a fourth picture would never have reached the model. Laying both crops into one tile keeps both of them on the wire inside that cap. The four legible bottle labels inside the sc04 crop were blanked to plain paper before sending, because round 3 already paid for the lesson that lettering in a reference comes back as pseudo-text at cfg 1." \
  --settings "PIL, sc04 crop (470,360,820,900) and sc12 crop (450,350,830,930), both scaled to 760px high and laid side by side, 1027x760 greyscale; scripts/make-abby-round4-tiles.py" \
  --prompt-text "Role line sent with the tile: THE BREED SHEET - TWO VIEWS OF THE ONE SAME ABBY, cut from the studio's own finished published plates, and it is the ONLY authority for how she is BUILT. Copy the harsh short double coat, the broad flat-topped skull, the small hard-edged triangular ears set close together on top of it, the short blunt rectangular muzzle with its beard fringe, the black studded collar with its pendant and the pale collared blouse buttoned over a modest chest. DO NOT copy its eyes, its open mouth, its gaze at the lens, its crop or its background. It is a chart of ONE character, not two: the gap down the middle is not drawn, and this tile never appears as a picture anywhere in the room." \
  --verdict "IT WORKED, AND IT IS THE ONE THING THAT DID. The Bichon is gone 6 of 6: every render in the round now carries the broad flat-topped skull, the small close-set triangular ears and the short blunt bearded muzzle of the accepted plates, where round 3 gave a round fluffy lapdog head with wide tufted ears in all six. The diptych did not leak - no render drew two Abbys, a gutter or a framed panel. What the tile did NOT fix, because it carries these faults itself and the EDITS could not out-argue it: the open blouse with a shading line between the breasts (both crops show it), and the fur running past the jaw down the throat (both crops show that too). The heart pendant came through on one seed of six." \
  "$D/abby-picture2-accepted-plates.png"

# --- the six renders ----------------------------------------------------------
file_one () {
  "$PY" "$L" --date 2026-09-06 --title "$2" --ask "$ASK" --thought "$3" \
    --settings "$SET, seed $1" --prompt-file "$D/abby-seed$1.prompt.txt" --verdict "$4" "$D/abby-seed$1.png"
}

file_one 55 "Abby character study, round 4, seed 55 - the ears finally read as a terrier's" "$T_COMMON Seed 55 first, as in round 3." \
  "RUNNER-UP OF SIX. The cleanest EAR read of the round and the thing the reference swap was for: two small hard-edged triangles carried erect and close-set on top of a broad flat skull, with the topknot between them, where round 3 gave wide-set tufted lapdog ears. The eye is second-best of the round - 24.6% below L60 with white measured at 253 and 253 against a paper of 254, so there is exact paper-white at both sides of the iris - and both pupils sit LEFT, onto Drew, so the founder's oldest complaint about her is finally answered on this seed. Nothing is lettered but the mirrored window; slate blank, every bottle label a blank panel. Marked below seed 44 on two counts: the back bar falls back into coarse dark hatch instead of the wood grain the EDIT asks for, and the bottom-left border breaks into spiked hatch fringe where the EDIT asks for a clean cut. The shared faults of the round are all here too - the lip parts on a gap, the coat runs past the jaw onto the throat, the blouse gapes."

file_one 41 "Abby character study, round 4, seed 41 - the only clean edge, the truest iris" "$T_COMMON Seed 41 is the recorded house seed." \
  "THIRD, and it holds the two things no other seed got. THE BORDER: it is the ONLY render of the six that answers the clean-edge EDIT - ink runs to a straight cut on all four sides, no spiked fringe, no washed band, no margin (measured mean edge tone 22 top, 25 bottom, 137 left, 35 right, against 187/229/219 on seed 44). THE IRIS: it is the only render that draws the chart's actual construction - a genuinely MID-GREY iris with a separate black pupil floating inside it - where the other seeds fuse iris and pupil into one dark disc with a grey rim. Its cost is the thinnest white margin of the round, 224 and 226 against a paper of 241, and the most frontal gaze of the six: the pupils sit near centre, so she reads closer to the lens than 55, 21 or 44. Quiet, clean, no strays, nothing lettered."

file_one 7 "Abby character study, round 4, seed 7 - the hardest coat and a fourth ear" "$T_COMMON" \
  "FOURTH. It draws the SHORTEST, HARDEST coat of the six and is the closest any render came to the harsh double coat the EDIT asks for - short straight strokes with tonal breaks, rather than the long silky sweep the other seeds kept. The eye is clean at 22.6% dark with white at 231 and 226 on a paper of 241. Two faults hold it down. FOUR EAR FORMS: extra ear-shaped tufts of fur stand outside both real ears, so the head reads with four pricked shapes instead of two. And the lip line opens on a visible tooth right of centre, where the EDIT says the lips touch along their whole length."

file_one 21 "Abby character study, round 4, seed 21 - the only heart pendant of the round" "$T_COMMON" \
  "FIFTH, and it carries one finding worth keeping: it is the ONLY seed of the six that drew the HEART pendant the judges asked for. Every other seed fell back to the old oval gem, which is canon's own fence wording ('a teardrop gem pendant') winning over the EDIT - so the heart IS reachable at this recipe and the fence is what is fighting it. Otherwise: gaze plainly left onto Drew, the best grey modelling under the jaw and along the far shoulder of the round, a good eye at 24.7% dark with white at 243 and 245 on a paper of 254. Faults: the same four-ear-form artifact as seed 7, and the bottom edge washes out into a pale band instead of cutting square."

file_one 33 "Abby character study, round 4, seed 33 - REJECT, the slate fills with pseudo-text" "$T_COMMON" \
  "REJECT, AND FATAL. The wiped slate has filled with a dense mass of letter-like glyphs - pseudo-text, which INSPECTION.md check 17 calls fatal on sight. This is the SAME seed that drew the eye chart into the slate in round 3, so seed 33 has a standing habit of filling that one panel: the hardened Picture 3 role line stopped the chart getting in but did not stop the scribble. It is also the only eye of the six to fail the white test, 187 on the far side of the iris against a paper of 238, and the only render whose near eye is the FAR one - her head has turned the wrong way. Recommendation: drop seed 33 from Abby's rotation; it has now failed the same check twice for the same reason."

file_one 44 "Abby character study, round 4, seed 44 - BEST OF THE ROUND" "$T_COMMON" \
  "BEST OF THE SIX, and the best Abby of the whole task so far. THE EYE IS THE BEST MEASURED OF ANY ROUND: 22.0% of the opening below L60, with the white on each side of the iris measured at 254 and 254 against a paper of 254 - both sclera crescents are EXACT paper white, clearly separated at the inner corner and the outer corner, which is precisely what the judges asked for and what no tile in the repository contains. THE GAZE IS OFF THE LENS: both pupils sit left, onto Drew, both eyes are on the page and the far eye is about four fifths the near one's width, so the head turn reads without losing an eye. THE BREED IS RIGHT: broad flat-topped skull wider than it is tall, two small close-set erect triangular ears and nothing extra, a short blunt muzzle with its beard fringe, a heavy black studded collar sitting up on the neck. THE ROOM IS RIGHT: back bar in readable wood grain with legible bottle silhouettes and clear glass, the counter crossing her at the waist, both hands working the glass and the towel, Drew and Barclay seated on the near side, the slate blank, every label a blank panel with no letterform anywhere. FOUR FAULTS REMAIN, and they are shared by every seed, so they are language and canon faults rather than seed faults: (1) the lip line still opens a dark gap; (2) the long coat still runs past the jaw down the throat and into the blouse; (3) the blouse still gapes with a shading line between the breasts; (4) the pendant is an oval, not the heart. The bottom-left border also frays into hatch fringe, which only seed 41 avoided."

# --- the sheet ----------------------------------------------------------------
"$PY" "$L" --date 2026-09-06 \
  --title "Abby round 4 - the contact sheet, six seeds against the tiles that were dropped" \
  --ask "$ASK" \
  --thought "$T_COMMON The sheet puts the six renders beside the two kit tiles this round dropped and the three references that were actually sent, so the swap can be judged by eye in one look: the old tiles draw a silky long-coated lapdog with wide tufted ears, the accepted plates draw a hard-coated terrier with small ears set close on top, and the renders now follow the second. Every panel carries its measured near-eye numbers from scripts/measure-abby-eye.py, so the eye is judged by number as the judges asked and not by impression." \
  --settings "PIL, 1702x2372 greyscale; scripts/build-abby-round4-sheet.py" \
  --prompt-text "Contact sheet: six renders at 420px beside canon/characters/abby/kit/bust.png and head.png (both dropped this round), the new Picture 2 breed sheet, the hand-drawn Picture 3 eye chart and the Picture 1 blank plate, each render labelled with its seed, its near-eye measurement and its verdict." \
  --verdict "THE ROUND IN ONE PICTURE. WON: the breed. The Bichon is gone 6 of 6 - flat-topped skull, small close-set triangular ears, blunt bearded muzzle in every render, against 0 of 6 in round 3. WON: the eye, by number - the near eye measures 22.0-26.8% below L60 across the five good seeds, and seed 44 puts exact paper white (254/254 on a paper of 254) at both sides of the iris. WON: the gaze, in 4 of 6 - the pupils sit left onto Drew where all six of round 3 stared at the reader. WON: the back bar, now wood grain with legible bottles in 4 of 6. LOST: the jawline, 6 of 6 - the coat still crosses onto the throat. LOST: the closed lip, 6 of 6. LOST: the modest blouse, 6 of 6. LOST: all three of Drew's fixes, 6 of 6 - his neck is still drawn in overlapping scales, still one unbroken C-hook, and only his EYE improved, which is the one Drew fix that landed. The reason is visible in the prompt: the auto-appended tail EDIT tells the model that everything other than the studied character stays exactly as Picture 1, and Picture 1 draws the scaled neck. Drew needs his own pass, or a corrected Picture 1. And three of the four remaining Abby faults are canon's own fence wording ('open two buttons over a smooth sleek throat', 'a teardrop gem pendant', 'a round soft fluffy westie head') being read AFTER the EDITS that contradict it - the fence, not the prompt, is now the thing fighting the judges." \
  "$D/sheet.png"
